name: update-site

on:
  schedule:
  - cron:  '0 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.5.3' # The R version to download (if necessary) and use.
    - name: run-script
      run: |
        Rscript -e "rmarkdown::render('dashboard.Rmd')"
        mv index.html docs
    - name: commit-changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Automated update"
        git commit -m "Automated update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.covid19 }}
