name: update-site

on:
  repository_dispatch:
    types: test-me
  schedule:
  - cron:  '0 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.5.3' # The R version to download (if necessary) and use.
    - uses: r-lib/actions/setup-pandoc@v1
    - name: Install rmarkdown
      run: |
        Rscript -e 'install.packages("rmarkdown")'
        Rscript -e 'install.packages("flexdashboard")'
        Rscript -e 'install.packages("tidyverse")'
        Rscript -e 'install.packages("lubridate")'
        Rscript -e 'install.packages("googlesheets")'
        Rscript -e 'install.packages("viridis")'
        Rscript -e 'install.packages("flexdashboard")'
        Rscript -e 'install.packages("here")'
        Rscript -e 'install.packages("rjson")'
        Rscript -e 'install.packages("jsonlite")'
        Rscript -e 'install.packages("RCurl")'
        Rscript -e 'install.packages("highcharter")'
        Rscript -e 'install.packages("here")'
        Rscript -e 'install.packages("viridisLite")'

    - name: run-script
      run: |
        Rscript -e "rmarkdown::render('dashboard.Rmd')"
        mv index.html docs
    - name: commit-changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Automated update"
        git commit -m "Automated update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.covid19 }}
